# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\work\kanban\UI\AddTaskWin.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_add_task(object):
    def setupUi(self, add_task):
        add_task.setObjectName("add_task")
        add_task.resize(600, 600)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(add_task)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.header_frame = QtWidgets.QFrame(add_task)
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setContentsMargins(8, 10, 8, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.header_label = QtWidgets.QLabel(self.header_frame)
        self.header_label.setText("")
        self.header_label.setObjectName("header_label")
        self.horizontalLayout.addWidget(self.header_label)
        spacerItem = QtWidgets.QSpacerItem(514, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.close_btn = QtWidgets.QPushButton(self.header_frame)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        self.verticalLayout_5.addWidget(self.header_frame)
        self.body_frame = QtWidgets.QFrame(add_task)
        self.body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body_frame.setObjectName("body_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.body_frame)
        self.verticalLayout_4.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.body_frame)
        self.splitter.setStyleSheet("alternate-background-color: rgb(255, 255, 255);")
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(6)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.task_title_line = QtWidgets.QLineEdit(self.layoutWidget)
        self.task_title_line.setText("")
        self.task_title_line.setObjectName("task_title_line")
        self.horizontalLayout_2.addWidget(self.task_title_line)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.task_plain = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.task_plain.setObjectName("task_plain")
        self.verticalLayout.addWidget(self.task_plain)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_3.addWidget(self.add_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.tags_list_widget = QtWidgets.QListWidget(self.layoutWidget1)
        self.tags_list_widget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tags_list_widget.setObjectName("tags_list_widget")
        self.verticalLayout_3.addWidget(self.tags_list_widget)
        self.set_remind_check = QtWidgets.QCheckBox(self.layoutWidget1)
        self.set_remind_check.setObjectName("set_remind_check")
        self.verticalLayout_3.addWidget(self.set_remind_check)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 6, -1)
        self.horizontalLayout_4.setSpacing(9)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.date_edit = QtWidgets.QDateEdit(self.layoutWidget1)
        self.date_edit.setEnabled(False)
        self.date_edit.setObjectName("date_edit")
        self.horizontalLayout_4.addWidget(self.date_edit)
        self.hour_combo = QtWidgets.QComboBox(self.layoutWidget1)
        self.hour_combo.setEnabled(False)
        self.hour_combo.setObjectName("hour_combo")
        self.horizontalLayout_4.addWidget(self.hour_combo)
        self.hour_label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hour_label.setFont(font)
        self.hour_label.setObjectName("hour_label")
        self.horizontalLayout_4.addWidget(self.hour_label)
        self.minute_combo = QtWidgets.QComboBox(self.layoutWidget1)
        self.minute_combo.setEnabled(False)
        self.minute_combo.setObjectName("minute_combo")
        self.horizontalLayout_4.addWidget(self.minute_combo)
        self.minute_label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minute_label.setFont(font)
        self.minute_label.setObjectName("minute_label")
        self.horizontalLayout_4.addWidget(self.minute_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.calendar_widget = QtWidgets.QCalendarWidget(self.layoutWidget1)
        self.calendar_widget.setEnabled(False)
        self.calendar_widget.setObjectName("calendar_widget")
        self.verticalLayout_3.addWidget(self.calendar_widget)
        self.verticalLayout_4.addWidget(self.splitter)
        self.verticalLayout_5.addWidget(self.body_frame)
        self.verticalLayout_5.setStretch(1, 1)

        self.retranslateUi(add_task)
        QtCore.QMetaObject.connectSlotsByName(add_task)

    def retranslateUi(self, add_task):
        _translate = QtCore.QCoreApplication.translate
        add_task.setWindowTitle(_translate("add_task", "Dialog"))
        self.close_btn.setText(_translate("add_task", "x"))
        self.task_title_line.setPlaceholderText(_translate("add_task", "为这个任务设置标题"))
        self.label_3.setText(_translate("add_task", "任务描述："))
        self.add_btn.setText(_translate("add_task", "添加任务"))
        self.label_4.setText(_translate("add_task", "设置标签："))
        self.set_remind_check.setText(_translate("add_task", "设置提醒"))
        self.hour_label.setText(_translate("add_task", "时"))
        self.minute_label.setText(_translate("add_task", "分"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_task = QtWidgets.QDialog()
    ui = Ui_add_task()
    ui.setupUi(add_task)
    add_task.show()
    sys.exit(app.exec_())

